[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = dolphin-mistral:7b-v2.8-q6_K
model_endpoint = http://host.docker.internal:11434
model_endpoint_type = ollama
model_wrapper = airoboros-l2-70b-2.1
context_window = 32768

[embedding]
embedding_endpoint_type = local
embedding_model = BAAI/bge-small-en-v1.5
embedding_dim = 384
embedding_chunk_size = 300

[archival_storage]
type = postgres
path = /root/.memgpt/chroma
uri = postgresql+pg8000://memgpt:memgpt@pgvector_db:5432/memgpt

[recall_storage]
type = postgres
path = /root/.memgpt
uri = postgresql+pg8000://memgpt:memgpt@pgvector_db:5432/memgpt

[metadata_storage]
type = postgres
path = /root/.memgpt
uri = postgresql+pg8000://memgpt:memgpt@pgvector_db:5432/memgpt

[version]
memgpt_version = 0.3.14

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

